# Generated by Django 6.1.1 on 2026-09-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_manager', 'Platform Manager'), ('school_admin', 'School Admin'), ('principal', 'Principal'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('secretary', 'Secretary'), ('parent', 'Parent'), ('student', 'Student')], default='school_admin', max_length=20),
        ),
    ]
