# Generated by Django 6.1.1 on 2026-09-16 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('records', '0001_initial'),
        ('schools', '0005_announcement_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='records.staffmember'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='records.student'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['school', 'role', 'is_active'], name='accounts_us_school__851d37_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['school', 'last_name', 'first_name'], name='accounts_us_school__9cd3ef_idx'),
        ),
    ]
