# Generated by Django 6.1.1 on 2026-09-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_password_reset_at_and_more'),
        ('records', '0007_resultentry_resultsheet_alter_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_students',
            field=models.ManyToManyField(blank=True, related_name='guardian_accounts', to='records.student'),
        ),
    ]
