# Generated by Django 6.1.1 on 2026-10-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_last_login_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
