# Generated by Django 6.1.1 on 2026-09-29 13:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        ('schools', '0009_admission_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_serial', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_enrolled', 'Not enrolled'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed')], default='not_enrolled', max_length=20)),
                ('activation_source', models.CharField(blank=True, choices=[('full_payment', 'Full verified payment'), ('admin_approval', 'Administrator approval'), ('migration', 'Existing student migration')], default='', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('review_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, default='', max_length=50)),
                ('scope', models.CharField(choices=[('class', 'Class'), ('level', 'Level'), ('school', 'School / session default')], default='school', max_length=10)),
                ('scope_key', models.CharField(default='*', max_length=20)),
                ('fee_type', models.CharField(choices=[('registration', 'Registration'), ('tuition', 'Tuition'), ('development', 'Development'), ('ict', 'ICT'), ('uniform', 'Uniform'), ('exam', 'Examination'), ('transport', 'Transport'), ('meals', 'Meals'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=datetime.date(1970, 1, 1))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scope', 'fee_type'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('NUR', 'NUR — Nursery'), ('PRI', 'PRI — Primary'), ('JSS', 'JSS — Junior Secondary'), ('SSS', 'SSS — Senior Secondary')], max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source',
            field=models.CharField(choices=[('admission', 'New admission'), ('bulk', 'Bulk generated'), ('migration', 'Migrated opening balance')], default='bulk', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_migration_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversal_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number_source',
            field=models.CharField(choices=[('school_assigned', 'School assigned'), ('system_generated', 'System generated'), ('imported', 'Imported')], default='school_assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school', 'status'], name='records_pay_school__be21d7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'status'], name='records_pay_invoice_63711f_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_name'], name='records_stu_school__8e88eb_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'status'], name='records_stu_school__1f8699_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='schools.school'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='records.academicsession'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['school', 'student'], name='records_inv_school__05d467_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['school', 'academic_session'], name='records_inv_school__b3a722_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('academic_session__isnull', False)), fields=('student', 'academic_session', 'term'), name='unique_invoice_per_student_session_term'),
        ),
        migrations.AddField(
            model_name='admissionsequence',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_sequences', to='schools.school'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='records.academicsession'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schools.school'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='records.student'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='records.academicsession'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='schools.school'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='records.academicsession'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='schools.school'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='level',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='schools.school'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='records.level'),
        ),
        migrations.AddField(
            model_name='admissionsequence',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_sequences', to='records.level'),
        ),
        migrations.AddField(
            model_name='registration',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='records.academicsession'),
        ),
        migrations.AddField(
            model_name='registration',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='records.invoice'),
        ),
        migrations.AddField(
            model_name='registration',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='schools.school'),
        ),
        migrations.AddField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='records.student'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='records.level'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='schools.school'),
        ),
        migrations.AddField(
            model_name='registration',
            name='intended_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='records.schoolclass'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='records.schoolclass'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='records.schoolclass'),
        ),
        migrations.AddField(
            model_name='section',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='records.schoolclass'),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.school'),
        ),
        migrations.AddField(
            model_name='registration',
            name='intended_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='records.section'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='records.section'),
        ),
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['school', 'is_current'], name='records_aca_school__fc5292_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_session_per_school'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.CheckConstraint(condition=models.Q(('end_year__gte', models.F('start_year'))), name='session_end_year_after_start'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('school', 'batch_code'), name='unique_import_batch_per_school'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_level_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='admissionsequence',
            constraint=models.UniqueConstraint(fields=('school', 'level', 'year'), name='unique_admission_sequence'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['school', 'level'], name='records_sch_school__f6cf04_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_class_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school', 'academic_session', 'is_active'], name='records_fee_school__b16d8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('school', 'academic_session', 'term', 'scope', 'scope_key', 'fee_type', 'effective_from'), name='unique_fee_structure_scope'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fee_structure_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school', 'class_obj'], name='records_sec_school__316f84_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('class_obj', 'name'), name='unique_section_per_class'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['school', 'status'], name='records_reg_school__7680f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('student', 'academic_session'), name='unique_registration_per_student_session'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school', 'academic_session', 'class_obj', 'section', 'status'], name='records_enr_school__b70f12_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school', 'status'], name='records_enr_school__e789e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'academic_session'), name='unique_active_enrollment_per_session'),
        ),
    ]
