# Generated by Django 6.1.1 on 2026-09-30 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_student_pending_payment_status'),
        ('schools', '0009_admission_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_per_student_session_term',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('academic_session__isnull', False), ('is_cancelled', False)), fields=('student', 'academic_session', 'term'), name='unique_invoice_per_student_session_term'),
        ),
    ]
