# Generated by Django 6.1.1 on 2026-09-30 18:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_backfill_fee_structure_rows'),
        ('schools', '0010_auditlog_after_auditlog_before_auditlog_entity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='', max_length=2)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ResultSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('assessment', models.CharField(max_length=100)),
                ('assessment_max', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6)),
                ('term', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('published', 'Published'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('correction_requested_at', models.DateTimeField(blank=True, null=True)),
                ('correction_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('not_enrolled', 'Not enrolled'), ('active', 'Active'), ('suspended', 'Suspended'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='not_enrolled', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('admitted', 'Admitted'), ('registering', 'Registering'), ('pending_payment', 'Pending payment'), ('cleared', 'Cleared'), ('enrolled', 'Enrolled'), ('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('transferred', 'Transferred'), ('expelled', 'Expelled')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'date', 'class_name'], name='records_att_school__e63659_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'student', 'date'], name='records_att_school__393191_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'status', 'class_name'], name='records_stu_school__8d725c_idx'),
        ),
        migrations.AddField(
            model_name='resultentry',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_entries', to='records.enrollment'),
        ),
        migrations.AddField(
            model_name='resultentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='records.student'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_sheets', to='records.academicsession'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_result_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_sheets', to='records.schoolclass'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='correction_authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised_result_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_result_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_sheets', to='schools.school'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_result_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultentry',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='records.resultsheet'),
        ),
        migrations.AddIndex(
            model_name='resultsheet',
            index=models.Index(fields=['school', 'academic_session', 'status'], name='records_res_school__f7f784_idx'),
        ),
        migrations.AddIndex(
            model_name='resultsheet',
            index=models.Index(fields=['school', 'class_obj', 'subject'], name='records_res_school__109098_idx'),
        ),
        migrations.AddConstraint(
            model_name='resultsheet',
            constraint=models.UniqueConstraint(fields=('school', 'academic_session', 'class_obj', 'subject', 'assessment', 'term'), name='unique_result_sheet'),
        ),
        migrations.AddIndex(
            model_name='resultentry',
            index=models.Index(fields=['student', 'sheet'], name='records_res_student_fd63cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='resultentry',
            constraint=models.UniqueConstraint(fields=('sheet', 'student'), name='unique_result_per_student_sheet'),
        ),
    ]
