# Generated by Django 6.1.1 on 2026-10-01 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_attendance_class_fk(apps, schema_editor):
    """Point legacy rows at their real `SchoolClass`.

    `class_name` is a free-text mirror, so this matches on name within each
    school. A row whose class no longer exists keeps a NULL `class_obj` rather
    than being attached to the wrong class.
    """
    AttendanceRecord = apps.get_model('records', 'AttendanceRecord')
    SchoolClass = apps.get_model('records', 'SchoolClass')
    db_alias = schema_editor.connection.alias

    for row in SchoolClass.objects.using(db_alias).values('id', 'name', 'school_id'):
        AttendanceRecord.objects.using(db_alias).filter(
            class_obj__isnull=True,
            class_name=row['name'],
            school_id=row['school_id'],
        ).update(class_obj_id=row['id'])


class Migration(migrations.Migration):

    dependencies = [
        # The dedupe must run before the constraint swap, otherwise the old
        # (student, date, subject) rows already conflict on (student, date).
        ('records', '0007b_attendance_dedupe_per_student_day'),
        ('schools', '0011_attendance_daily_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['class_obj__sort_order', 'class_obj__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_attendance_per_student_day',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='records.schoolclass'),
        ),
        # Backfill class_obj from the mirrored class_name, so history and the
        # class overview can index the FK rather than a free-text string.
        migrations.RunPython(
            backfill_attendance_class_fk,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'class_obj', 'date'], name='records_att_school__66960f_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_attendance_per_student_day'),
        ),
        migrations.AddField(
            model_name='classteacherassignment',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='records.academicsession'),
        ),
        migrations.AddField(
            model_name='classteacherassignment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='records.schoolclass'),
        ),
        migrations.AddField(
            model_name='classteacherassignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='schools.school'),
        ),
        migrations.AddField(
            model_name='classteacherassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='records.staffmember'),
        ),
        migrations.AddIndex(
            model_name='classteacherassignment',
            index=models.Index(fields=['school', 'class_obj'], name='records_cla_school__a57109_idx'),
        ),
        migrations.AddIndex(
            model_name='classteacherassignment',
            index=models.Index(fields=['school', 'staff'], name='records_cla_school__9b025f_idx'),
        ),
        migrations.AddConstraint(
            model_name='classteacherassignment',
            constraint=models.UniqueConstraint(fields=('class_obj', 'academic_session'), name='unique_class_teacher_per_session'),
        ),
    ]
