# Generated by Django 6.1.1 on 2026-10-01 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_attendance_daily_register'),
        ('schools', '0013_auditlog_merge_duplicate_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['school', '-created_at'], name='records_inv_school__8249a5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school', '-created_at'], name='records_pay_school__f3cf27_idx'),
        ),
    ]
