# Generated by Django 6.1.1 on 2026-10-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_invoice_records_inv_school__8249a5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultentry',
            name='assignment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='resultentry',
            name='ca1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='resultentry',
            name='ca2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='resultentry',
            name='exam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
