# Generated by Django 6.1.1 on 2026-10-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_resultentry_result_ca1_within_max_and_more'),
        ('schools', '0014_backfill_class_mirror'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetablePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_break', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_periods', to='schools.school')),
            ],
            options={
                'ordering': ['sort_order', 'start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, default='', max_length=60)),
                ('weekday', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='records.schoolclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='schools.school')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='records.staffmember')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='records.timetableperiod')),
            ],
            options={
                'ordering': ['weekday', 'period__sort_order', 'class_obj__sort_order', 'class_obj__name'],
            },
        ),
        migrations.AddIndex(
            model_name='timetableperiod',
            index=models.Index(fields=['school', 'sort_order'], name='records_tim_school__87a491_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetableperiod',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_period_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='timetableperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='period_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['class_obj', 'weekday', 'period'], name='tt_class_week_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['teacher', 'weekday', 'period'], name='tt_teacher_week_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('school', 'weekday', 'period', 'class_obj'), name='unique_timetable_class_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher__isnull', False)), fields=('school', 'weekday', 'period', 'teacher'), name='unique_timetable_teacher_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('room', ''), _negated=True), fields=('school', 'weekday', 'period', 'room'), name='unique_timetable_room_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='timetable_weekday_range'),
        ),
    ]
