# Generated by Django 6.1.1 on 2026-10-03 15:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_timetable_module'),
        ('schools', '0014_backfill_class_mirror'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=40)),
                ('objectives', models.TextField()),
                ('previous_knowledge', models.TextField(blank=True, default='')),
                ('introduction', models.TextField(blank=True, default='')),
                ('teacher_activities', models.TextField(blank=True, default='')),
                ('student_activities', models.TextField(blank=True, default='')),
                ('materials', models.TextField(blank=True, default='')),
                ('assessment', models.TextField(blank=True, default='')),
                ('homework', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='records.academicsession')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='records.schoolclass')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='schools.school')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['school', 'academic_session', 'class_obj'], name='records_les_school__300890_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1), ('duration_minutes__lte', 240)), name='lesson_plan_duration_range')],
            },
        ),
        migrations.CreateModel(
            name='PromotionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promote_min_average', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('promote_min_attendance', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=5)),
                ('conditional_min_average', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('conditional_min_attendance', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('conditional_max_failed_subjects', models.PositiveSmallIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_policy', to='schools.school')),
            ],
            options={
                'constraints': [
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ('promote_min_average__gte', 0),
                                ('promote_min_average__lte', 100),
                                ('promote_min_attendance__gte', 0),
                                ('promote_min_attendance__lte', 100),
                                ('conditional_min_average__gte', 0),
                                ('conditional_min_average__lte', 100),
                                ('conditional_min_attendance__gte', 0),
                                ('conditional_min_attendance__lte', 100),
                                ('conditional_min_average__lte', models.F('promote_min_average')),
                                ('conditional_min_attendance__lte', models.F('promote_min_attendance')),
                                ('conditional_max_failed_subjects__lte', 20),
                            )
                        ),
                        name='promotion_policy_ranges',
                    ),
                ],
            },
        ),
    ]
