# Generated by Django 6.1.1 on 2026-10-07 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_lessonplan_promotionpolicy'),
        ('schools', '0016_announcement_target_academic_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('school', 'reference'), name='unique_payment_reference_per_school'),
        ),
    ]
