# Generated by Django 6.1.1 on 2026-10-08 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_alter_payment_reference_and_more'),
        ('schools', '0017_subscriptionplan_ai_cost_per_credit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(max_length=30)),
                ('term', models.CharField(blank=True, default='', max_length=50)),
                ('reminder_rule', models.CharField(blank=True, default='', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='records.student')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['school', 'student', 'reminder_type', 'term'], name='records_rem_school__f278e0_idx'), models.Index(fields=['school', 'sent_at'], name='records_rem_school__8ea2b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('sms', 'SMS'), ('otp', 'OTP'), ('ai', 'AI')], max_length=10)),
                ('action_type', models.CharField(choices=[('payment_notification', 'Payment notification'), ('balance_reminder', 'Balance reminder'), ('otp_send', 'OTP send'), ('ai_request', 'AI request'), ('ai_proposal', 'AI proposal'), ('ai_confirmation', 'AI confirmation')], max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=100)),
                ('estimated_cost', models.PositiveIntegerField(default=0)),
                ('actual_cost', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('pending', 'Pending'), ('exhausted', 'Allowance exhausted')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='records.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='records.payment')),
                ('result_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='records.resultsheet')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='records.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'resource_type', 'created_at'], name='records_usa_school__90d3c8_idx'), models.Index(fields=['school', 'resource_type', 'action_type'], name='records_usa_school__77cdd6_idx'), models.Index(fields=['school', 'status'], name='records_usa_school__b1d377_idx'), models.Index(fields=['student', 'resource_type'], name='records_usa_student_3296c1_idx'), models.Index(fields=['user', 'resource_type'], name='records_usa_user_id_c9e37e_idx'), models.Index(fields=['invoice', 'resource_type'], name='records_usa_invoice_897505_idx'), models.Index(fields=['payment', 'resource_type'], name='records_usa_payment_156e00_idx')],
            },
        ),
    ]
