# Generated by Django 6.1.1 on 2026-10-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_reminderlog_usagerecord'),
        ('schools', '0017_subscriptionplan_ai_cost_per_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='term_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='reminderlog',
            constraint=models.UniqueConstraint(fields=('school', 'student', 'reminder_type', 'term', 'reminder_rule'), name='unique_reminder_per_rule'),
        ),
    ]
