# Generated by Django 6.1.1 on 2026-10-10 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_student_staff_public_id'),
        ('schools', '0018_school_attendance_radius_school_gps_accuracy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('check_in_at', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('at_school', 'At school'), ('outside', 'Outside the campus'), ('unverified', 'Location unavailable'), ('pending_review', 'Pending review')], max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=280)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='schools.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='records.staffmember')),
            ],
            options={
                'ordering': ['-date', '-check_in_at'],
                'indexes': [models.Index(fields=['school', 'date'], name='records_sta_school__cbe0f5_idx'), models.Index(fields=['school', 'status', 'date'], name='records_sta_school__8a7bd7_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff', 'date'), name='unique_staff_attendance_per_day')],
            },
        ),
    ]
