# Generated by Django 6.1.1 on 2026-09-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_active'], name='schools_sch_is_acti_522730_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['state'], name='schools_sch_state_c19d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolsubscription',
            index=models.Index(fields=['status'], name='schools_sch_status_c43d14_idx'),
        ),
    ]
