# Generated by Django 6.1.1 on 2026-09-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_schools_sch_is_acti_522730_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='current_session',
            field=models.CharField(default='2025/2026', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='current_term',
            field=models.CharField(default='First Term', max_length=50),
        ),
    ]
