# Generated by Django 6.1.1 on 2026-09-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_current_session_school_current_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, default='', max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
