# Generated by Django 6.1.1 on 2026-09-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_announcement_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='classes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='school',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
