# Generated by Django 6.1.1 on 2026-09-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_classes_school_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='fee_structure',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
