# Generated by Django 6.1.1 on 2026-09-24 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_fee_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['school'], name='schools_aud_school__11e839_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='schools_aud_created_7bb752_idx'),
        ),
    ]
