# Generated by Django 6.1.1 on 2026-09-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auditlog_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
