# Generated by Django 6.1.1 on 2026-10-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_auditlog_after_auditlog_before_auditlog_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='attendance_weekend_days',
            field=models.JSONField(blank=True, default=[5, 6], db_default=[5, 6]),
        ),
        migrations.AddField(
            model_name='school',
            name='non_school_days',
            field=models.JSONField(blank=True, default=list, db_default=[]),
        ),
    ]
