# Generated by Django 6.1.1 on 2026-10-01 10:24

import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_attendance_daily_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='attendance_weekend_days',
            field=models.JSONField(
                blank=True,
                default=schools.models._default_attendance_weekend_days,
                db_default=[5, 6],
            ),
        ),
    ]
