# Generated by Django 6.1.1 on 2026-10-01 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_attendance_calendar_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['school', 'action'], name='schools_aud_school__004e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['school', 'entity', 'entity_id'], name='schools_aud_school__619bf9_idx'),
        ),
    ]
