# Generated by Django 6.1.1 on 2026-10-05 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_lessonplan_promotionpolicy'),
        ('schools', '0015_alter_announcement_options_announcement_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='records.academicsession'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='records.schoolclass'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='records.section'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['school', 'target_class'], name='schools_ann_school__55afdb_idx'),
        ),
    ]
