# Generated by Django 6.1.1 on 2026-10-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_announcement_target_academic_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_cost_per_credit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_ai_allowance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_otp_allowance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_sms_allowance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='otp_cost_per_unit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sms_cost_per_unit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
