# Generated by Django 6.1.1 on 2026-10-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_subscriptionplan_ai_cost_per_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='attendance_radius',
            field=models.PositiveIntegerField(db_default=150, default=150),
        ),
        migrations.AddField(
            model_name='school',
            name='gps_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='location_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='location_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='timezone',
            field=models.CharField(db_default='Africa/Lagos', default='Africa/Lagos', max_length=64),
        ),
    ]
