# Generated by Django 6.1.1 on 2026-10-10 15:52

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_school_attendance_radius_school_gps_accuracy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['sort_order', 'min_students']},
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='override_active',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='override_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='override_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='code',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='storage_gb',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='schoolsubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('paystack_reference', models.CharField(blank=True, default='', max_length=100)),
                ('access_code', models.CharField(blank=True, default='', max_length=100)),
                ('authorization_url', models.URLField(blank=True, default='')),
                ('amount_kobo', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(db_default='NGN', default='NGN', max_length=8)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('renewal', 'Renewal'), ('plan_change', 'Plan change')], default='renewal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('channel', models.CharField(blank=True, default='', max_length=40)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='schools.subscriptionplan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['school', '-created_at'], name='schools_sub_school__8bf37f_idx'), models.Index(fields=['status'], name='schools_sub_status_0de260_idx')],
            },
        ),
    ]
