/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppAcademicsRouteImport } from './routes/_app.academics'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppChildrenRouteImport } from './routes/_app.children'
import { Route as AppCommunicationRouteImport } from './routes/_app.communication'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFeesRouteImport } from './routes/_app.fees'
import { Route as AppLessonPlansRouteImport } from './routes/_app.lesson-plans'
import { Route as AppMyClassesRouteImport } from './routes/_app.my-classes'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPromotionRouteImport } from './routes/_app.promotion'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppResultsRouteImport } from './routes/_app.results'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppSubscriptionRouteImport } from './routes/_app.subscription'
import { Route as AppSyncRouteImport } from './routes/_app.sync'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as AppUssdRouteImport } from './routes/_app.ussd'
import { Route as AppFinanceIndexRouteImport } from './routes/_app.finance.index'
import { Route as AppFinanceInvoicesRouteImport } from './routes/_app.finance.invoices'
import { Route as AppPlatformIndexRouteImport } from './routes/_app.platform.index'
import { Route as AppPlatformAnalyticsRouteImport } from './routes/_app.platform.analytics'
import { Route as AppPlatformSchoolsRouteImport } from './routes/_app.platform.schools'
import { Route as AppPlatformSecurityRouteImport } from './routes/_app.platform.security'
import { Route as AppPlatformSubscriptionsRouteImport } from './routes/_app.platform.subscriptions'
import { Route as AppPlatformSupportRouteImport } from './routes/_app.platform.support'
import { Route as AppStaffIndexRouteImport } from './routes/_app.staff.index'
import { Route as AppStaffStaffIdRouteImport } from './routes/_app.staff.$staffId'
import { Route as AppStaffNewRouteImport } from './routes/_app.staff.new'
import { Route as AppStudentsIndexRouteImport } from './routes/_app.students.index'
import { Route as AppStudentsStudentIdRouteImport } from './routes/_app.students.$studentId'
import { Route as AppStudentsImportRouteImport } from './routes/_app.students.import'
import { Route as AppStudentsNewRouteImport } from './routes/_app.students.new'
import { Route as AppStaffStaffIdIndexRouteImport } from './routes/_app.staff.$staffId.index'
import { Route as AppStaffStaffIdEditRouteImport } from './routes/_app.staff.$staffId.edit'
import { Route as AppStudentsStudentIdIndexRouteImport } from './routes/_app.students.$studentId.index'
import { Route as AppStudentsStudentIdEditRouteImport } from './routes/_app.students.$studentId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAcademicsRoute = AppAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenRoute = AppChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationRoute = AppCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonPlansRoute = AppLessonPlansRouteImport.update({
  id: '/lesson-plans',
  path: '/lesson-plans',
  getParentRoute: () => AppRoute,
} as any)
const AppMyClassesRoute = AppMyClassesRouteImport.update({
  id: '/my-classes',
  path: '/my-classes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPromotionRoute = AppPromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSyncRoute = AppSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppUssdRoute = AppUssdRouteImport.update({
  id: '/ussd',
  path: '/ussd',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceInvoicesRoute = AppFinanceInvoicesRouteImport.update({
  id: '/finance/invoices',
  path: '/finance/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformIndexRoute = AppPlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformAnalyticsRoute = AppPlatformAnalyticsRouteImport.update({
  id: '/platform/analytics',
  path: '/platform/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformSchoolsRoute = AppPlatformSchoolsRouteImport.update({
  id: '/platform/schools',
  path: '/platform/schools',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformSecurityRoute = AppPlatformSecurityRouteImport.update({
  id: '/platform/security',
  path: '/platform/security',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformSubscriptionsRoute =
  AppPlatformSubscriptionsRouteImport.update({
    id: '/platform/subscriptions',
    path: '/platform/subscriptions',
    getParentRoute: () => AppRoute,
  } as any)
const AppPlatformSupportRoute = AppPlatformSupportRouteImport.update({
  id: '/platform/support',
  path: '/platform/support',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIndexRoute = AppStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStaffRoute,
} as any)
const AppStaffStaffIdRoute = AppStaffStaffIdRouteImport.update({
  id: '/$staffId',
  path: '/$staffId',
  getParentRoute: () => AppStaffRoute,
} as any)
const AppStaffNewRoute = AppStaffNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppStaffRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsImportRoute = AppStudentsImportRouteImport.update({
  id: '/students/import',
  path: '/students/import',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsNewRoute = AppStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffStaffIdIndexRoute = AppStaffStaffIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStaffStaffIdRoute,
} as any)
const AppStaffStaffIdEditRoute = AppStaffStaffIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppStaffStaffIdRoute,
} as any)
const AppStudentsStudentIdIndexRoute =
  AppStudentsStudentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)
const AppStudentsStudentIdEditRoute =
  AppStudentsStudentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/academics': typeof AppAcademicsRoute
  '/accounts': typeof AppAccountsRoute
  '/ai': typeof AppAiRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/children': typeof AppChildrenRoute
  '/communication': typeof AppCommunicationRoute
  '/dashboard': typeof AppDashboardRoute
  '/fees': typeof AppFeesRoute
  '/lesson-plans': typeof AppLessonPlansRoute
  '/my-classes': typeof AppMyClassesRoute
  '/profile': typeof AppProfileRoute
  '/promotion': typeof AppPromotionRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRouteWithChildren
  '/subscription': typeof AppSubscriptionRoute
  '/sync': typeof AppSyncRoute
  '/timetable': typeof AppTimetableRoute
  '/ussd': typeof AppUssdRoute
  '/finance/invoices': typeof AppFinanceInvoicesRoute
  '/platform/analytics': typeof AppPlatformAnalyticsRoute
  '/platform/schools': typeof AppPlatformSchoolsRoute
  '/platform/security': typeof AppPlatformSecurityRoute
  '/platform/subscriptions': typeof AppPlatformSubscriptionsRoute
  '/platform/support': typeof AppPlatformSupportRoute
  '/staff/$staffId': typeof AppStaffStaffIdRouteWithChildren
  '/staff/new': typeof AppStaffNewRoute
  '/students/$studentId': typeof AppStudentsStudentIdRouteWithChildren
  '/students/import': typeof AppStudentsImportRoute
  '/students/new': typeof AppStudentsNewRoute
  '/finance/': typeof AppFinanceIndexRoute
  '/platform/': typeof AppPlatformIndexRoute
  '/staff/': typeof AppStaffIndexRoute
  '/students/': typeof AppStudentsIndexRoute
  '/staff/$staffId/edit': typeof AppStaffStaffIdEditRoute
  '/students/$studentId/edit': typeof AppStudentsStudentIdEditRoute
  '/staff/$staffId/': typeof AppStaffStaffIdIndexRoute
  '/students/$studentId/': typeof AppStudentsStudentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/academics': typeof AppAcademicsRoute
  '/accounts': typeof AppAccountsRoute
  '/ai': typeof AppAiRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/children': typeof AppChildrenRoute
  '/communication': typeof AppCommunicationRoute
  '/dashboard': typeof AppDashboardRoute
  '/fees': typeof AppFeesRoute
  '/lesson-plans': typeof AppLessonPlansRoute
  '/my-classes': typeof AppMyClassesRoute
  '/profile': typeof AppProfileRoute
  '/promotion': typeof AppPromotionRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/sync': typeof AppSyncRoute
  '/timetable': typeof AppTimetableRoute
  '/ussd': typeof AppUssdRoute
  '/finance/invoices': typeof AppFinanceInvoicesRoute
  '/platform/analytics': typeof AppPlatformAnalyticsRoute
  '/platform/schools': typeof AppPlatformSchoolsRoute
  '/platform/security': typeof AppPlatformSecurityRoute
  '/platform/subscriptions': typeof AppPlatformSubscriptionsRoute
  '/platform/support': typeof AppPlatformSupportRoute
  '/staff/new': typeof AppStaffNewRoute
  '/students/import': typeof AppStudentsImportRoute
  '/students/new': typeof AppStudentsNewRoute
  '/finance': typeof AppFinanceIndexRoute
  '/platform': typeof AppPlatformIndexRoute
  '/staff': typeof AppStaffIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/staff/$staffId/edit': typeof AppStaffStaffIdEditRoute
  '/students/$studentId/edit': typeof AppStudentsStudentIdEditRoute
  '/staff/$staffId': typeof AppStaffStaffIdIndexRoute
  '/students/$studentId': typeof AppStudentsStudentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/academics': typeof AppAcademicsRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/children': typeof AppChildrenRoute
  '/_app/communication': typeof AppCommunicationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fees': typeof AppFeesRoute
  '/_app/lesson-plans': typeof AppLessonPlansRoute
  '/_app/my-classes': typeof AppMyClassesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/promotion': typeof AppPromotionRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRouteWithChildren
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_app/sync': typeof AppSyncRoute
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/ussd': typeof AppUssdRoute
  '/_app/finance/invoices': typeof AppFinanceInvoicesRoute
  '/_app/platform/analytics': typeof AppPlatformAnalyticsRoute
  '/_app/platform/schools': typeof AppPlatformSchoolsRoute
  '/_app/platform/security': typeof AppPlatformSecurityRoute
  '/_app/platform/subscriptions': typeof AppPlatformSubscriptionsRoute
  '/_app/platform/support': typeof AppPlatformSupportRoute
  '/_app/staff/$staffId': typeof AppStaffStaffIdRouteWithChildren
  '/_app/staff/new': typeof AppStaffNewRoute
  '/_app/students/$studentId': typeof AppStudentsStudentIdRouteWithChildren
  '/_app/students/import': typeof AppStudentsImportRoute
  '/_app/students/new': typeof AppStudentsNewRoute
  '/_app/finance/': typeof AppFinanceIndexRoute
  '/_app/platform/': typeof AppPlatformIndexRoute
  '/_app/staff/': typeof AppStaffIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/_app/staff/$staffId/edit': typeof AppStaffStaffIdEditRoute
  '/_app/students/$studentId/edit': typeof AppStudentsStudentIdEditRoute
  '/_app/staff/$staffId/': typeof AppStaffStaffIdIndexRoute
  '/_app/students/$studentId/': typeof AppStudentsStudentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/get-started'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/academics'
    | '/accounts'
    | '/ai'
    | '/attendance'
    | '/audit-logs'
    | '/children'
    | '/communication'
    | '/dashboard'
    | '/fees'
    | '/lesson-plans'
    | '/my-classes'
    | '/profile'
    | '/promotion'
    | '/reports'
    | '/results'
    | '/settings'
    | '/staff'
    | '/subscription'
    | '/sync'
    | '/timetable'
    | '/ussd'
    | '/finance/invoices'
    | '/platform/analytics'
    | '/platform/schools'
    | '/platform/security'
    | '/platform/subscriptions'
    | '/platform/support'
    | '/staff/$staffId'
    | '/staff/new'
    | '/students/$studentId'
    | '/students/import'
    | '/students/new'
    | '/finance/'
    | '/platform/'
    | '/staff/'
    | '/students/'
    | '/staff/$staffId/edit'
    | '/students/$studentId/edit'
    | '/staff/$staffId/'
    | '/students/$studentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/get-started'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/academics'
    | '/accounts'
    | '/ai'
    | '/attendance'
    | '/audit-logs'
    | '/children'
    | '/communication'
    | '/dashboard'
    | '/fees'
    | '/lesson-plans'
    | '/my-classes'
    | '/profile'
    | '/promotion'
    | '/reports'
    | '/results'
    | '/settings'
    | '/subscription'
    | '/sync'
    | '/timetable'
    | '/ussd'
    | '/finance/invoices'
    | '/platform/analytics'
    | '/platform/schools'
    | '/platform/security'
    | '/platform/subscriptions'
    | '/platform/support'
    | '/staff/new'
    | '/students/import'
    | '/students/new'
    | '/finance'
    | '/platform'
    | '/staff'
    | '/students'
    | '/staff/$staffId/edit'
    | '/students/$studentId/edit'
    | '/staff/$staffId'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/get-started'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/_app/academics'
    | '/_app/accounts'
    | '/_app/ai'
    | '/_app/attendance'
    | '/_app/audit-logs'
    | '/_app/children'
    | '/_app/communication'
    | '/_app/dashboard'
    | '/_app/fees'
    | '/_app/lesson-plans'
    | '/_app/my-classes'
    | '/_app/profile'
    | '/_app/promotion'
    | '/_app/reports'
    | '/_app/results'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/subscription'
    | '/_app/sync'
    | '/_app/timetable'
    | '/_app/ussd'
    | '/_app/finance/invoices'
    | '/_app/platform/analytics'
    | '/_app/platform/schools'
    | '/_app/platform/security'
    | '/_app/platform/subscriptions'
    | '/_app/platform/support'
    | '/_app/staff/$staffId'
    | '/_app/staff/new'
    | '/_app/students/$studentId'
    | '/_app/students/import'
    | '/_app/students/new'
    | '/_app/finance/'
    | '/_app/platform/'
    | '/_app/staff/'
    | '/_app/students/'
    | '/_app/staff/$staffId/edit'
    | '/_app/students/$studentId/edit'
    | '/_app/staff/$staffId/'
    | '/_app/students/$studentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/academics': {
      id: '/_app/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AppAcademicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/children': {
      id: '/_app/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof AppChildrenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communication': {
      id: '/_app/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AppCommunicationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees': {
      id: '/_app/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lesson-plans': {
      id: '/_app/lesson-plans'
      path: '/lesson-plans'
      fullPath: '/lesson-plans'
      preLoaderRoute: typeof AppLessonPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-classes': {
      id: '/_app/my-classes'
      path: '/my-classes'
      fullPath: '/my-classes'
      preLoaderRoute: typeof AppMyClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promotion': {
      id: '/_app/promotion'
      path: '/promotion'
      fullPath: '/promotion'
      preLoaderRoute: typeof AppPromotionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sync': {
      id: '/_app/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AppSyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ussd': {
      id: '/_app/ussd'
      path: '/ussd'
      fullPath: '/ussd'
      preLoaderRoute: typeof AppUssdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/': {
      id: '/_app/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/invoices': {
      id: '/_app/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof AppFinanceInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/': {
      id: '/_app/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof AppPlatformIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/analytics': {
      id: '/_app/platform/analytics'
      path: '/platform/analytics'
      fullPath: '/platform/analytics'
      preLoaderRoute: typeof AppPlatformAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/schools': {
      id: '/_app/platform/schools'
      path: '/platform/schools'
      fullPath: '/platform/schools'
      preLoaderRoute: typeof AppPlatformSchoolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/security': {
      id: '/_app/platform/security'
      path: '/platform/security'
      fullPath: '/platform/security'
      preLoaderRoute: typeof AppPlatformSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/subscriptions': {
      id: '/_app/platform/subscriptions'
      path: '/platform/subscriptions'
      fullPath: '/platform/subscriptions'
      preLoaderRoute: typeof AppPlatformSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/support': {
      id: '/_app/platform/support'
      path: '/platform/support'
      fullPath: '/platform/support'
      preLoaderRoute: typeof AppPlatformSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/': {
      id: '/_app/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AppStaffIndexRouteImport
      parentRoute: typeof AppStaffRoute
    }
    '/_app/staff/$staffId': {
      id: '/_app/staff/$staffId'
      path: '/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AppStaffStaffIdRouteImport
      parentRoute: typeof AppStaffRoute
    }
    '/_app/staff/new': {
      id: '/_app/staff/new'
      path: '/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof AppStaffNewRouteImport
      parentRoute: typeof AppStaffRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$studentId': {
      id: '/_app/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/import': {
      id: '/_app/students/import'
      path: '/students/import'
      fullPath: '/students/import'
      preLoaderRoute: typeof AppStudentsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/new': {
      id: '/_app/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AppStudentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/$staffId/': {
      id: '/_app/staff/$staffId/'
      path: '/'
      fullPath: '/staff/$staffId/'
      preLoaderRoute: typeof AppStaffStaffIdIndexRouteImport
      parentRoute: typeof AppStaffStaffIdRoute
    }
    '/_app/staff/$staffId/edit': {
      id: '/_app/staff/$staffId/edit'
      path: '/edit'
      fullPath: '/staff/$staffId/edit'
      preLoaderRoute: typeof AppStaffStaffIdEditRouteImport
      parentRoute: typeof AppStaffStaffIdRoute
    }
    '/_app/students/$studentId/': {
      id: '/_app/students/$studentId/'
      path: '/'
      fullPath: '/students/$studentId/'
      preLoaderRoute: typeof AppStudentsStudentIdIndexRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
    '/_app/students/$studentId/edit': {
      id: '/_app/students/$studentId/edit'
      path: '/edit'
      fullPath: '/students/$studentId/edit'
      preLoaderRoute: typeof AppStudentsStudentIdEditRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
  }
}

interface AppStaffStaffIdRouteChildren {
  AppStaffStaffIdEditRoute: typeof AppStaffStaffIdEditRoute
  AppStaffStaffIdIndexRoute: typeof AppStaffStaffIdIndexRoute
}

const AppStaffStaffIdRouteChildren: AppStaffStaffIdRouteChildren = {
  AppStaffStaffIdEditRoute: AppStaffStaffIdEditRoute,
  AppStaffStaffIdIndexRoute: AppStaffStaffIdIndexRoute,
}

const AppStaffStaffIdRouteWithChildren = AppStaffStaffIdRoute._addFileChildren(
  AppStaffStaffIdRouteChildren,
)

interface AppStaffRouteChildren {
  AppStaffStaffIdRoute: typeof AppStaffStaffIdRouteWithChildren
  AppStaffNewRoute: typeof AppStaffNewRoute
  AppStaffIndexRoute: typeof AppStaffIndexRoute
}

const AppStaffRouteChildren: AppStaffRouteChildren = {
  AppStaffStaffIdRoute: AppStaffStaffIdRouteWithChildren,
  AppStaffNewRoute: AppStaffNewRoute,
  AppStaffIndexRoute: AppStaffIndexRoute,
}

const AppStaffRouteWithChildren = AppStaffRoute._addFileChildren(
  AppStaffRouteChildren,
)

interface AppStudentsStudentIdRouteChildren {
  AppStudentsStudentIdEditRoute: typeof AppStudentsStudentIdEditRoute
  AppStudentsStudentIdIndexRoute: typeof AppStudentsStudentIdIndexRoute
}

const AppStudentsStudentIdRouteChildren: AppStudentsStudentIdRouteChildren = {
  AppStudentsStudentIdEditRoute: AppStudentsStudentIdEditRoute,
  AppStudentsStudentIdIndexRoute: AppStudentsStudentIdIndexRoute,
}

const AppStudentsStudentIdRouteWithChildren =
  AppStudentsStudentIdRoute._addFileChildren(AppStudentsStudentIdRouteChildren)

interface AppRouteChildren {
  AppAcademicsRoute: typeof AppAcademicsRoute
  AppAccountsRoute: typeof AppAccountsRoute
  AppAiRoute: typeof AppAiRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppChildrenRoute: typeof AppChildrenRoute
  AppCommunicationRoute: typeof AppCommunicationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeesRoute: typeof AppFeesRoute
  AppLessonPlansRoute: typeof AppLessonPlansRoute
  AppMyClassesRoute: typeof AppMyClassesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPromotionRoute: typeof AppPromotionRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRouteWithChildren
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppSyncRoute: typeof AppSyncRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppUssdRoute: typeof AppUssdRoute
  AppFinanceInvoicesRoute: typeof AppFinanceInvoicesRoute
  AppPlatformAnalyticsRoute: typeof AppPlatformAnalyticsRoute
  AppPlatformSchoolsRoute: typeof AppPlatformSchoolsRoute
  AppPlatformSecurityRoute: typeof AppPlatformSecurityRoute
  AppPlatformSubscriptionsRoute: typeof AppPlatformSubscriptionsRoute
  AppPlatformSupportRoute: typeof AppPlatformSupportRoute
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRouteWithChildren
  AppStudentsImportRoute: typeof AppStudentsImportRoute
  AppStudentsNewRoute: typeof AppStudentsNewRoute
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
  AppPlatformIndexRoute: typeof AppPlatformIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicsRoute: AppAcademicsRoute,
  AppAccountsRoute: AppAccountsRoute,
  AppAiRoute: AppAiRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppChildrenRoute: AppChildrenRoute,
  AppCommunicationRoute: AppCommunicationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeesRoute: AppFeesRoute,
  AppLessonPlansRoute: AppLessonPlansRoute,
  AppMyClassesRoute: AppMyClassesRoute,
  AppProfileRoute: AppProfileRoute,
  AppPromotionRoute: AppPromotionRoute,
  AppReportsRoute: AppReportsRoute,
  AppResultsRoute: AppResultsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRouteWithChildren,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppSyncRoute: AppSyncRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppUssdRoute: AppUssdRoute,
  AppFinanceInvoicesRoute: AppFinanceInvoicesRoute,
  AppPlatformAnalyticsRoute: AppPlatformAnalyticsRoute,
  AppPlatformSchoolsRoute: AppPlatformSchoolsRoute,
  AppPlatformSecurityRoute: AppPlatformSecurityRoute,
  AppPlatformSubscriptionsRoute: AppPlatformSubscriptionsRoute,
  AppPlatformSupportRoute: AppPlatformSupportRoute,
  AppStudentsStudentIdRoute: AppStudentsStudentIdRouteWithChildren,
  AppStudentsImportRoute: AppStudentsImportRoute,
  AppStudentsNewRoute: AppStudentsNewRoute,
  AppFinanceIndexRoute: AppFinanceIndexRoute,
  AppPlatformIndexRoute: AppPlatformIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
